const baseURL = '/images/symbol';

// chain info key
export const CHAIN = {
  COSMOS: 'cosmos',
  IRIS: 'iris',
  BAND: 'band',
  KAVA: 'kava',
  AKASH: 'akash',
  CERTIK: 'certik',
  SENTINEL: 'sentinel',
  PERSISTENCE: 'persistence',
  FETCH_AI: 'fetch-ai',
  SIFCHAIN: 'sifchain',
  CRYPTO_ORG: 'crypto-org',
  KICHAIN: 'kichain',
  STARNAME: 'starname',
  MEDIBLOC: 'medibloc',
  EMONEY: 'emoney',
  RIZON: 'rizon',
  JUNO: 'juno',
} as const;

// chain info key === path
export const chains = {
  [CHAIN.COSMOS]: {
    name: 'cosmos',
    path: CHAIN.COSMOS,
    imgURL: `${baseURL}/cosmos.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'cosmos',
    },
    lcdURL: 'https://lcd-cosmos.cosmostation.io',
    symbolName: 'ATOM',
    denom: 'uatom',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'cosmos',
  },
  [CHAIN.IRIS]: {
    name: 'iris',
    path: CHAIN.IRIS,
    imgURL: `${baseURL}/iris.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'iaa',
    },
    lcdURL: 'https://lcd-iris.cosmostation.io',
    symbolName: 'IRIS',
    denom: 'uiris',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'iris-network',
  },
  [CHAIN.KAVA]: {
    name: 'kava',
    path: CHAIN.KAVA,
    imgURL: `${baseURL}/kava.png`,
    hdPath: '44/118/0/0/0',
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'kava',
    },
    lcdURL: 'https://lcd-kava.cosmostation.io',
    symbolName: 'KAVA',
    denom: 'ukava',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'kava',
  },
  [CHAIN.BAND]: {
    name: 'band',
    path: CHAIN.BAND,
    imgURL: `${baseURL}/band.png`,
    hdPath: '44/494/0/0/0',
    wallet: {
      hdPath: '44/494/0/0/0',
      prefix: 'band',
    },
    lcdURL: 'https://lcd-band.cosmostation.io',
    symbolName: 'BAND',
    denom: 'uband',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'band-protocol',
  },
  [CHAIN.AKASH]: {
    name: 'akash',
    path: CHAIN.AKASH,
    imgURL: `${baseURL}/akash.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'akash',
    },
    lcdURL: 'https://lcd-akash.cosmostation.io',
    symbolName: 'AKT',
    denom: 'uakt',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'akash-network',
  },
  [CHAIN.CERTIK]: {
    name: 'certik',
    path: CHAIN.CERTIK,
    imgURL: `${baseURL}/certik.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'certik',
    },
    lcdURL: 'https://lcd-certik.cosmostation.io',
    symbolName: 'CTK',
    denom: 'uctk',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'certik',
  },
  [CHAIN.SENTINEL]: {
    name: 'sentinel',
    path: CHAIN.SENTINEL,
    imgURL: `${baseURL}/sentinel.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'sent',
    },
    lcdURL: 'https://lcd-sentinel.cosmostation.io',
    symbolName: 'DVPN',
    denom: 'udvpn',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'sentinel-group',
  },
  [CHAIN.PERSISTENCE]: {
    name: 'persistence',
    path: CHAIN.PERSISTENCE,
    imgURL: `${baseURL}/persistence.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'persistence',
    },
    lcdURL: 'https://lcd-persistence.cosmostation.io',
    symbolName: 'XPRT',
    denom: 'uxprt',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'persistence',
  },
  [CHAIN.FETCH_AI]: {
    name: 'fetch.ai',
    path: CHAIN.FETCH_AI,
    imgURL: `${baseURL}/fetch-ai.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'fetch',
    },
    lcdURL: 'https://lcd-fetchai.cosmostation.io',
    symbolName: 'FET',
    denom: 'afet',
    decimal: 0.000000000000000001,
    decimalLength: 18,
    coingeckoId: 'fetch-ai',
  },
  [CHAIN.SIFCHAIN]: {
    name: 'sifchain',
    path: CHAIN.SIFCHAIN,
    imgURL: `${baseURL}/sifchain.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'sif',
    },
    lcdURL: 'https://lcd-sifchain.cosmostation.io',
    symbolName: 'ROWAN',
    denom: 'rowan',
    decimal: 0.000000000000000001,
    decimalLength: 18,
    coingeckoId: 'sifchain',
  },
  [CHAIN.CRYPTO_ORG]: {
    name: 'crypto.org',
    path: CHAIN.CRYPTO_ORG,
    imgURL: `${baseURL}/crypto-org.png`,
    wallet: {
      hdPath: '44/394/0/0/0',
      prefix: 'cro',
    },
    lcdURL: 'https://lcd-cryptocom.cosmostation.io',
    symbolName: 'CRO',
    denom: 'basecro',
    decimal: 0.00000001,
    decimalLength: 8,
    coingeckoId: 'crypto-com-chain',
  },
  [CHAIN.KICHAIN]: {
    name: 'kichain',
    path: CHAIN.KICHAIN,
    imgURL: `${baseURL}/kichain.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'ki',
    },
    lcdURL: 'https://lcd-kichain.cosmostation.io',
    symbolName: 'XKI',
    denom: 'uxki',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'ki',
  },
  [CHAIN.STARNAME]: {
    name: 'starname',
    path: CHAIN.STARNAME,
    imgURL: `${baseURL}/starname.png`,
    wallet: {
      hdPath: '44/234/0/0/0',
      prefix: 'star',
    },
    lcdURL: 'https://lcd-iov.cosmostation.io',
    symbolName: 'IOV',
    denom: 'uiov',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'starname',
  },
  [CHAIN.MEDIBLOC]: {
    name: 'medibloc',
    path: CHAIN.MEDIBLOC,
    imgURL: `${baseURL}/medibloc.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'panacea',
    },
    lcdURL: 'https://lcd-medibloc.cosmostation.io',
    symbolName: 'MED',
    denom: 'umed',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'medibloc',
  },
  [CHAIN.EMONEY]: {
    name: 'emoney',
    path: CHAIN.EMONEY,
    imgURL: `${baseURL}/emoney.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'emoney',
    },
    lcdURL: 'https://lcd-emoney.cosmostation.io',
    symbolName: 'NGM',
    denom: 'ungm',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'e-money',
  },
  [CHAIN.RIZON]: {
    name: 'rizon',
    path: CHAIN.RIZON,
    imgURL: `${baseURL}/rizon.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'rizon',
    },
    lcdURL: 'https://lcd-rizon.cosmostation.io',
    symbolName: 'ATOLO',
    denom: 'uatolo',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'hdac',
  },
  [CHAIN.JUNO]: {
    name: 'juno',
    path: CHAIN.JUNO,
    imgURL: `${baseURL}/juno.png`,
    wallet: {
      hdPath: '44/118/0/0/0',
      prefix: 'juno',
    },
    lcdURL: 'https://lcd-juno.cosmostation.io',
    symbolName: 'JUNO',
    denom: 'ujuno',
    decimal: 0.000001,
    decimalLength: 6,
    coingeckoId: 'juno-network',
  },
} as const;

export const chainNames = Object.values(chains).map((chain) => chain.name);
export const chainGeckoIds = Object.values(chains).map((chain) => chain.coingeckoId);

export const chainPaths = Object.values(CHAIN);

export type ChainPath = typeof chainPaths[number];
export type ChainGeckoId = typeof chainGeckoIds[number];
