export const CHAIN = {
  AKASH: 'akash',
  BAND: 'band',
  CERTIK: 'certik',
  COSMOS: 'cosmos',
  CRYPTOCOM: 'cryptocom',
  EMONEY: 'emoney',
  FETCHAI: 'fetchai',
  IRIS: 'iris',
  JUNO: 'juno',
  KAVA: 'kava',
  KICHAIN: 'kichain',
  MEDIBLOC: 'medibloc',
  OSMOSIS: 'osmosis',
  PERSISTENCE: 'persistence',
  RIZON: 'rizon',
  SENTINEL: 'sentinel',
  SIFCHAIN: 'sifchain',
  STARNAME: 'starname',
} as const;
